adding bsd-3 clause license
atoum/prophecy-extension pull request #2
Opened 2016-09-28 11:22 UTC by marcomenzel

referring to #1

2016-10-02 15:25 UTC, jubianchi requested changes

2016-10-02 15:25 UTC, jubianchi commented on README.md
> +atoum Prophecy extension is released under the BSD-3-Clause License. See the bundled LICENSE file for details.
`s/Prophecy extension/prophecy-extension/`

2016-10-02 19:53 UTC, marcomenzel commented
at some time I will get this atoum naming thing ;-)

2016-10-04 07:34 UTC, Hywan commented
Do we have a conflict with #7?

2016-11-11 11:01 UTC, jubianchi approved these changes

2016-11-11 11:01 UTC, merged